name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      # Composer Install
      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-progress --no-suggest --ignore-platform-reqs

      # Node Install
      - name: Node install Dependencies
        run: npm install

      # Build Assets
      - name: Build assets
        run: |
          npm run production
          rm -rf node_modules && npm install --production

      # Update Version
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Update Version in WordPress files
        run: |
          sed -i 's/\(\s*\)\*\(\s*\)Version:\(\s*\)[^,]*/\1*\2Version:\3${{ env.RELEASE_VERSION }}/g' src/WSForm_Login.php
          sed -i -E 's/([[:blank:]]*\$version[[:blank:]]*=[[:blank:]]*")(.*)(".*)/\1${{ env.RELEASE_VERSION }}\3/' src/WSForm_Login.php
          sed -i 's/Stable tag:\(\s*\)[^,]*/Stable tag:\1${{ env.RELEASE_VERSION }}/g' README.txt

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            ${{ github.event.repository.name }}.php
            README.txt
          commit-msg: Update Version in WordPress specific files
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: juvo-ws-form-login
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: wsform-login-${{ env.RELEASE_VERSION }}
          tag_name: ${{ env.RELEASE_VERSION }}
          files: ${{ steps.deploy.outputs.zip-path }}
