name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: cache-composer
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-prod-${{ hashFiles('composer.lock') }}

      - name: Install dependencies
        if: steps.cache-composer.outputs.cache-hit != 'true'
        run: composer install --no-dev --prefer-dist --no-interaction --no-progress

      # Update Version
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Update Version in WordPress files
        run: |
          sed -i 's/\(\s*\)\*\(\s*\)Version:\(\s*\)[^,]*/\1*\2Version:\3${{ env.RELEASE_VERSION }}/g' ${{ github.event.repository.name }}.php
          sed -i 's/Stable tag:\(\s*\)[^,]*/Stable tag:\1${{ env.RELEASE_VERSION }}/g' readme.txt

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            ${{ github.event.repository.name }}.php
            readme.txt
          commit-msg: Update Version in WordPress specific files
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: juvo-mail-editor