name: Test/Analyse

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: cache-composer
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-dev-${{ hashFiles('composer.lock') }}

      - name: Install dependencies
        if: steps.cache-composer.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Cache Composer (Test) packages
        id: cache-composer-test
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-dev-test-${{ hashFiles('./tests/setup/composer.lock') }}

      - name: Install (Test) dependencies
        if: steps.cache-composer-test.outputs.cache-hit != 'true'
        run: |
          cd ./tests/setup
          composer config http-basic.plugins.juvo-design.de ${{ secrets.SATISPRESS_KEY }} satispress
          composer install

      - name: Cache npm packages
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: npm-dev-${{ hashFiles('package-lock.json') }}

      - name: Install npm dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install

      - name: Build assets
        run: |
          npm run production

      - name: PHPSTAN
        run: composer run static-analyse

      - name: Run integration Tests
        run: |
          npm run test:e2e
